name: Build and deploy [develop]
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 54.244.140.20
        username: root
        password: latadigital
        port: 22
        script: |
          ./test.sh